apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: wasm-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wasm-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

          # wymaga: kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml