apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: wasm-keda
spec:
  hosts:
    - wasm.local
  scaleTargetRef:
    name: wasm-app
    kind: Deployment
    apiVersion: apps/v1
    service: wasm-service
    port: 80
  replicas:
    min: 0
    max: 10
  scalingMetric:
    requestRate:
      targetValue: 15
      window: 1m
