apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: wasm-keda
spec:
  scaleTargetRef:
    name: wasm-app
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        metricName: http_requests_total
        threshold: "100"
        query: sum(rate(http_requests_total[1m]))